-- MySQL Script generated by MySQL Workbench
-- Sun Sep  1 16:15:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema OC_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OC_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OC_Database` DEFAULT CHARACTER SET utf8 ;
USE `OC_Database` ;

-- -----------------------------------------------------
-- Table `OC_Database`.`Mode de paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Mode de paiement` (
  `Choix_paiement` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Choix_paiement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Client` (
  `Numero_de_client` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(30) NOT NULL,
  `nom` VARCHAR(30) NOT NULL,
  `adresse_mail` VARCHAR(50) NOT NULL,
  `telephone` CHAR(10) NOT NULL,
  `mot_de_passe` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Numero_de_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Ville` (
  `Id_ville` INT NOT NULL AUTO_INCREMENT,
  `nom_ville` VARCHAR(60) NOT NULL,
  `code_postal` CHAR(6) NOT NULL,
  PRIMARY KEY (`Id_ville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Adresse` (
  `Id_adresse` INT NOT NULL AUTO_INCREMENT,
  `libelle_voie` INT NOT NULL,
  `complement_libelle` VARCHAR(30) NOT NULL,
  `Ville_id` INT NOT NULL,
  PRIMARY KEY (`Id_adresse`, `Ville_id`),
  INDEX `fk_Adresse_Ville1_idx` (`Ville_id` ASC),
  CONSTRAINT `fk_Adresse_Ville1`
    FOREIGN KEY (`Ville_id`)
    REFERENCES `OC_Database`.`Ville` (`Id_ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Statut_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Statut_commande` (
  `Statut_commande_id` INT NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Statut_commande_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Commande` (
  `Numero_commande` INT NOT NULL AUTO_INCREMENT,
  `date_commande` DATE NOT NULL,
  `Client_Numero_de_client` INT NOT NULL,
  `Adresse_Id_adresse` INT NOT NULL,
  `Mode de paiement_Choix_paiement` INT NOT NULL,
  `Statut commande_Statut_commande_id` INT NOT NULL,
  PRIMARY KEY (`Numero_commande`),
  INDEX `fk_Commande_Client1_idx` (`Client_Numero_de_client` ASC),
  INDEX `fk_Commande_Adresse1_idx` (`Adresse_Id_adresse` ASC),
  INDEX `fk_Commande_Mode de paiement1_idx` (`Mode de paiement_Choix_paiement` ASC),
  INDEX `fk_Commande_Statut commande1_idx` (`Statut commande_Statut_commande_id` ASC),
  CONSTRAINT `fk_Commande_Client1`
    FOREIGN KEY (`Client_Numero_de_client`)
    REFERENCES `OC_Database`.`Client` (`Numero_de_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Adresse1`
    FOREIGN KEY (`Adresse_Id_adresse`)
    REFERENCES `OC_Database`.`Adresse` (`Id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Mode de paiement1`
    FOREIGN KEY (`Mode de paiement_Choix_paiement`)
    REFERENCES `OC_Database`.`Mode de paiement` (`Choix_paiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Statut commande1`
    FOREIGN KEY (`Statut commande_Statut_commande_id`)
    REFERENCES `OC_Database`.`Statut_commande` (`Statut_commande_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Magasin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Magasin` (
  `Id_magasin` INT NOT NULL AUTO_INCREMENT,
  `nom_magasin` VARCHAR(30) NOT NULL,
  `Adresse_Id_adresse` INT NOT NULL,
  PRIMARY KEY (`Id_magasin`, `Adresse_Id_adresse`),
  INDEX `fk_Magasin_Adresse1_idx` (`Adresse_Id_adresse` ASC),
  CONSTRAINT `fk_Magasin_Adresse1`
    FOREIGN KEY (`Adresse_Id_adresse`)
    REFERENCES `OC_Database`.`Adresse` (`Id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Ingredient` (
  `Id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Pizza` (
  `Id_pizza` INT NOT NULL AUTO_INCREMENT,
  `recette_pizza` LONGTEXT NOT NULL,
  `libelle` VARCHAR(120) NOT NULL,
  `prix` DOUBLE NOT NULL,
  PRIMARY KEY (`Id_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Pizza_has_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Pizza_has_Ingredient` (
  `Id_pizza` INT NOT NULL,
  `Id_ingredient` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`Id_pizza`, `Id_ingredient`),
  INDEX `fk_Pizza_has_Ingredient_Ingredient1_idx` (`Id_ingredient` ASC),
  INDEX `fk_Pizza_has_Ingredient_Pizza1_idx` (`Id_pizza` ASC),
  CONSTRAINT `fk_Pizza_has_Ingredient_Pizza1`
    FOREIGN KEY (`Id_pizza`)
    REFERENCES `OC_Database`.`Pizza` (`Id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_has_Ingredient_Ingredient1`
    FOREIGN KEY (`Id_ingredient`)
    REFERENCES `OC_Database`.`Ingredient` (`Id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Magasin_has_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Magasin_has_Ingredient` (
  `Id_magasin` INT NOT NULL,
  `Id_ingredient` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`Id_magasin`, `Id_ingredient`),
  INDEX `fk_Magasin_has_Ingredient_Ingredient1_idx` (`Id_ingredient` ASC),
  INDEX `fk_Magasin_has_Ingredient_Magasin1_idx` (`Id_magasin` ASC),
  CONSTRAINT `fk_Magasin_has_Ingredient_Magasin1`
    FOREIGN KEY (`Id_magasin`)
    REFERENCES `OC_Database`.`Magasin` (`Id_magasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magasin_has_Ingredient_Ingredient1`
    FOREIGN KEY (`Id_ingredient`)
    REFERENCES `OC_Database`.`Ingredient` (`Id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Commande_has_Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Commande_has_Pizza` (
  `Numero_commande` INT NOT NULL,
  `Id_pizza` INT NOT NULL,
  `quantite` INT NOT NULL,
  `prix` DOUBLE NOT NULL,
  `libelle` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`Numero_commande`, `Id_pizza`),
  INDEX `fk_Commande_has_Pizza_Pizza1_idx` (`Id_pizza` ASC),
  INDEX `fk_Commande_has_Pizza_Commande1_idx` (`Numero_commande` ASC),
  CONSTRAINT `fk_Commande_has_Pizza_Commande1`
    FOREIGN KEY (`Numero_commande`)
    REFERENCES `OC_Database`.`Commande` (`Numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Pizza_Pizza1`
    FOREIGN KEY (`Id_pizza`)
    REFERENCES `OC_Database`.`Pizza` (`Id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OC_Database`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OC_Database`.`Facture` (
  `Numero_facture` INT NOT NULL AUTO_INCREMENT,
  `date_facture` DATE NOT NULL,
  `description` VARCHAR(60) NOT NULL,
  `Commande_Numero_commande` INT NOT NULL,
  PRIMARY KEY (`Numero_facture`, `Commande_Numero_commande`),
  INDEX `fk_Facture_Commande1_idx` (`Commande_Numero_commande` ASC),
  CONSTRAINT `fk_Facture_Commande1`
    FOREIGN KEY (`Commande_Numero_commande`)
    REFERENCES `OC_Database`.`Commande` (`Numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
